package architecture

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// nxsLayers defines the five NXS layers in canonical order.
var nxsLayers = []layerDef{
	{"governance", 1, "Governance", "Config, standards, quality gates — the rules the system obeys."},
	{"orchestration", 2, "Orchestration", "CLI entrypoints and run wiring. Owns no business logic."},
	{"execution", 3, "Execution", "Core domain logic — pure, no I/O."},
	{"persistence", 4, "Persistence", "Driven adapters: file I/O, external tools, serialization."},
	{"surface", 5, "Surface", "Output: reports, annotations, rendered artifacts."},
}

type layerDef struct {
	ID    string
	Order int
	Label string
	Role  string
}

// WriteArchManifest generates .coderev/architecture.toml from scanned packages.
// It is idempotent and best-effort (failure does not abort the scan).
func WriteArchManifest(target string, pkgs []PackageInfo, flows []Flow) {
	dir := filepath.Join(target, ".coderev")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	f, err := os.Create(filepath.Join(dir, "architecture.toml"))
	if err != nil {
		return
	}
	defer f.Close()
	writeManifest(f, target, pkgs, flows)
}

func writeManifest(w io.Writer, target string, pkgs []PackageInfo, flows []Flow) {
	name := filepath.Base(target)
	fmt.Fprintf(w, "# Generated by coderev — do not commit; edit to add context.\n")
	fmt.Fprintf(w, "# Schema: nexovia/2 — https://github.com/nex-ovia/NXS\n\n")
	writeProjectSection(w, name)
	writeArchSection(w)
	writeFlows(w, flows)
	writeComponents(w, pkgs)
	writeLinks(w, pkgs)
}

func writeProjectSection(w io.Writer, name string) {
	fmt.Fprintf(w, "[project]\n")
	fmt.Fprintf(w, "name      = %q\n", name)
	fmt.Fprintf(w, "kind      = \"cli\"\n")
	fmt.Fprintf(w, "domain    = \"software\"\n")
	fmt.Fprintf(w, "source    = \"scan\"\n")
	fmt.Fprintf(w, "schema    = \"nexovia/2\"\n")
	fmt.Fprintf(w, "status    = \"active\"\n")
	fmt.Fprintf(w, "generated = %q\n\n", time.Now().UTC().Format(time.RFC3339))
}

func writeArchSection(w io.Writer) {
	fmt.Fprintf(w, "[architecture]\n")
	fmt.Fprintf(w, "pattern         = \"NXS\"\n")
	fmt.Fprintf(w, "dependency_rule = \"core-independent\"\n")
	fmt.Fprintf(w, "basis           = [\"hexagonal (ports & adapters)\"]\n\n")
	for _, l := range nxsLayers {
		fmt.Fprintf(w, "[architecture.layers.%s]\n", l.ID)
		fmt.Fprintf(w, "order = %d\n", l.Order)
		fmt.Fprintf(w, "label = %q\n", l.Label)
		fmt.Fprintf(w, "role  = %q\n\n", l.Role)
	}
}

func writeFlows(w io.Writer, flows []Flow) {
	if len(flows) == 0 {
		return
	}
	for _, f := range flows {
		fmt.Fprintf(w, "[[flows]]\n")
		fmt.Fprintf(w, "name        = %q\n", f.Name)
		fmt.Fprintf(w, "entry       = %q\n", f.Entry)
		fmt.Fprintf(w, "description = %q\n", f.Description)
		for _, s := range f.Steps {
			fmt.Fprintf(w, "[[flows.steps]]\n")
			fmt.Fprintf(w, "file  = %q\n", s.File)
			fmt.Fprintf(w, "func  = %q\n", s.Func)
			fmt.Fprintf(w, "layer = %q\n", s.Layer)
			fmt.Fprintf(w, "label = %q\n", s.Label)
		}
		fmt.Fprintf(w, "\n")
	}
}

func writeComponents(w io.Writer, pkgs []PackageInfo) {
	sorted := make([]PackageInfo, len(pkgs))
	copy(sorted, pkgs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ImportPath < sorted[j].ImportPath })
	for _, p := range sorted {
		writeComponent(w, p)
	}
}

func writeComponent(w io.Writer, p PackageInfo) {
	id := componentID(p.ImportPath)
	fmt.Fprintf(w, "[components.%s]\n", id)
	fmt.Fprintf(w, "label   = %q\n", componentLabel(p))
	fmt.Fprintf(w, "path    = %q\n", p.ImportPath)
	fmt.Fprintf(w, "kind    = \"module\"\n")
	fmt.Fprintf(w, "layer   = %q\n", p.Layer)
	fmt.Fprintf(w, "status  = \"active\"\n")
	fmt.Fprintf(w, "summary = %q\n", p.DocSummary)
	fmt.Fprintf(w, "tags    = []\n")
	fmt.Fprintf(w, "functions = [%s]\n", quotedList(p.ExportedSymbols))
	fmt.Fprintf(w, "libraries = [%s]\n", quotedList(p.ExternalLibs))
	if len(p.Files) > 0 {
		fileKeys := make([]string, 0, len(p.Files))
		for k := range p.Files {
			fileKeys = append(fileKeys, k)
		}
		sort.Strings(fileKeys)
		for _, f := range fileKeys {
			fid := componentID(f)
			syms := p.Files[f]
			if len(syms) == 0 {
				continue
			}
			fmt.Fprintf(w, "\n[components.%s.files.%s]\n", id, fid)
			for _, s := range syms {
				fmt.Fprintf(w, "  %q\n", s)
			}
		}
	}
	fmt.Fprintf(w, "\n[components.%s.provenance]\n", id)
	fmt.Fprintf(w, "summary = { by = \"scan\", confidence = 0.7 }\n\n")
}

func writeLinks(w io.Writer, pkgs []PackageInfo) {
	type link struct{ from, to string }
	seen := map[string]bool{}
	var links []link
	for _, p := range pkgs {
		from := componentID(p.ImportPath)
		for _, dep := range p.Deps {
			to := componentID(dep)
			key := from + "→" + to
			if seen[key] {
				continue
			}
			seen[key] = true
			links = append(links, link{from, to})
		}
	}
	sort.Slice(links, func(i, j int) bool {
		if links[i].from != links[j].from {
			return links[i].from < links[j].from
		}
		return links[i].to < links[j].to
	})
	for _, l := range links {
		fmt.Fprintf(w, "[[links]]\n")
		fmt.Fprintf(w, "from       = %q\n", l.from)
		fmt.Fprintf(w, "to         = %q\n", l.to)
		fmt.Fprintf(w, "relation   = \"depends_on\"\n")
		fmt.Fprintf(w, "provenance = { by = \"scan\", confidence = 1.0 }\n\n")
	}
}

// componentID converts an import path to a safe TOML key.
func componentID(importPath string) string {
	if importPath == "" {
		return "root"
	}
	r := strings.NewReplacer("/", "_", "-", "_", ".", "_")
	return r.Replace(importPath)
}

func componentLabel(p PackageInfo) string {
	parts := strings.Split(p.ImportPath, "/")
	return parts[len(parts)-1]
}

func quotedList(items []string) string {
	if len(items) == 0 {
		return ""
	}
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}
