package report

import (
	"fmt"
	"os"
	"strings"

	"github.com/srivastava-ami/coderev/internal/analysis"
)

// GenerateMarkdown writes an interactive Markdown report to outputPath.
// Uses <details>/<summary> for collapsible sections, Mermaid for graphs,
// and standard tables — renders natively on GitHub, VS Code, and any MD viewer.
func GenerateMarkdown(r Report, outputPath string) error {
	var b strings.Builder
	writeMarkdown(&b, r)
	return os.WriteFile(outputPath, []byte(b.String()), 0o644)
}

func writeMarkdown(b *strings.Builder, r Report) {
	statusIcon := "✅"
	if r.Summary.OverallStatus == "FAIL" {
		statusIcon = "❌"
	}

	fmt.Fprintf(b, "# Code Review Report: %s\n\n", r.Meta.RepoName)
	fmt.Fprintf(b, "> %s **%s** · %d findings · %d blocker(s) · %d major · %d advisory  \n",
		statusIcon, r.Summary.OverallStatus,
		r.Summary.TotalFindings,
		r.Summary.BySeverity["blocker"],
		r.Summary.BySeverity["major"],
		r.Summary.BySeverity["advisory"],
	)
	fmt.Fprintf(b, "> Scanned **%d files** · Generated %s  \n", r.Summary.TotalFiles, r.Meta.Generated)
	if r.Meta.StandardsVersion != "" {
		fmt.Fprintf(b, "> Standards: `%s` v%s\n\n", r.Meta.StandardsFile, r.Meta.StandardsVersion)
	} else {
		fmt.Fprintf(b, "> Standards: `%s`\n\n", r.Meta.StandardsFile)
	}
	writeDeltaLine(b, r)
	b.WriteString("---\n\n")

	writeSummaryTable(b, r)
	writePillarSections(b, r)
	writeFileHeatmap(b, r)
	writeExceptions(b, r)
	writeWarnings(b, r)

	b.WriteString("---\n\n")
	fmt.Fprintf(b, "*Generated by [coderev™](https://github.com/srivastava-ami/coderev) — built by Amit Srivastava · %s*\n", r.Meta.Generated)
}

func writeSummaryTable(b *strings.Builder, r Report) {
	b.WriteString("## Summary\n\n")
	b.WriteString("| Severity | Count |\n|----------|-------|\n")
	fmt.Fprintf(b, "| 🔴 Blocker | %d |\n", r.Summary.BySeverity["blocker"])
	fmt.Fprintf(b, "| 🟡 Major | %d |\n", r.Summary.BySeverity["major"])
	fmt.Fprintf(b, "| 🔵 Advisory | %d |\n", r.Summary.BySeverity["advisory"])
	fmt.Fprintf(b, "| **Total** | **%d** |\n\n", r.Summary.TotalFindings)
	if len(r.Summary.ByPillar) > 0 {
		b.WriteString("<details>\n<summary>Findings by pillar</summary>\n\n")
		b.WriteString("| Pillar | Count |\n|--------|-------|\n")
		for pillar, count := range r.Summary.ByPillar {
			fmt.Fprintf(b, "| %s | %d |\n", pillar, count)
		}
		b.WriteString("\n</details>\n\n")
	}
}

func writePillarSections(b *strings.Builder, r Report) {
	if len(r.Pillars) == 0 {
		return
	}
	b.WriteString("## Findings by Pillar\n\n")
	for _, p := range r.Pillars {
		blockers := countBlockers(p.Findings)
		icon := "🟡"
		if p.Status == "FAIL" {
			icon = "🔴"
		}
		ratingBadge := ratingBadge(p.Rating)
		fmt.Fprintf(b, "<details>\n<summary>%s <b>%s</b> %s — %d finding(s)", icon, p.Name, ratingBadge, len(p.Findings))
		if blockers > 0 {
			fmt.Fprintf(b, " · %d blocker(s)", blockers)
		}
		b.WriteString("</summary>\n\n")
		writeFindingsTable(b, p.Findings)
		b.WriteString("</details>\n\n")
	}
}

func writeFindingsTable(b *strings.Builder, findings []analysis.Finding) {
	b.WriteString("| File | Line | Rule | Severity | Message |\n")
	b.WriteString("|------|------|------|----------|---------|\n")
	for _, f := range findings {
		fmt.Fprintf(b, "| `%s` | %d | `%s` | %s | %s |\n",
			shortenPath(f.File), f.Line, f.Rule, severityIcon(f.Severity), mdEscape(f.Message))
		if f.Remediation != "" {
			fmt.Fprintf(b, "| | | | | 💡 *%s* |\n", mdEscape(f.Remediation))
		}
	}
	b.WriteString("\n")
}

func writeFileHeatmap(b *strings.Builder, r Report) {
	hot := hotFileCount(r.Files)
	if hot == 0 {
		return
	}
	b.WriteString("## Hot Files\n\n")
	fmt.Fprintf(b, "<details>\n<summary>%d file(s) with findings</summary>\n\n", hot)
	b.WriteString("| File | Language | Lines | Findings | Heat |\n")
	b.WriteString("|------|----------|-------|----------|------|\n")
	shown := 0
	for _, f := range r.Files {
		if len(f.Findings) == 0 {
			continue
		}
		fmt.Fprintf(b, "| `%s` | %s | %d | %d | %s |\n",
			shortenPath(f.Path), f.Language, f.Lines, len(f.Findings), heatBar(f.HeatScore))
		shown++
		if shown >= 30 {
			break
		}
	}
	b.WriteString("\n</details>\n\n")
}

func hotFileCount(files []FileResult) int {
	n := 0
	for _, f := range files {
		if len(f.Findings) > 0 {
			n++
		}
	}
	return n
}

func writeExceptions(b *strings.Builder, r Report) {
	if len(r.Exceptions) == 0 {
		return
	}
	hasContent := false
	for _, e := range r.Exceptions {
		if e.FileOrModule != "" || e.Rule != "" {
			hasContent = true
			break
		}
	}
	if !hasContent {
		return
	}
	b.WriteString("<details>\n<summary>Exceptions / suppressions</summary>\n\n")
	b.WriteString("| File / Module | Rule | Justification |\n|---------------|------|---------------|\n")
	for _, e := range r.Exceptions {
		if e.FileOrModule == "" && e.Rule == "" {
			continue
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", e.FileOrModule, e.Rule, mdEscape(e.Justification))
	}
	b.WriteString("\n</details>\n\n")
}

func writeWarnings(b *strings.Builder, r Report) {
	if len(r.Warnings) == 0 {
		return
	}
	b.WriteString("<details>\n<summary>⚠️ Adapter warnings</summary>\n\n")
	for _, w := range r.Warnings {
		fmt.Fprintf(b, "- **%s**: %s\n", w.Adapter, w.Reason)
	}
	b.WriteString("\n</details>\n\n")
}
